name: Android CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Java (Android requires a specific version of Java)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Grant execute permission for the Gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the Android project
      - name: Build with Gradle
        run: ./gradlew build

      # Run unit tests (optional but recommended)
      - name: Run tests
        run: ./gradlew test

      # Upload the APK as an artifact (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      # Security Testing with OWASP Dependency-Check
      - name: Run OWASP Dependency-Check
        uses: dependency-check/github-action@v3
        with:
          format: "HTML"
          output-directory: "dependency-check-report"

      # Upload OWASP Dependency-Check Report (optional)
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/
