name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK for the build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Validate Gradle Wrapper
      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper

      # Step 4: Build the project
      - name: Build Project
        run: ./gradlew build --no-daemon

      # Step 5: SonarCloud Analysis
      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=Webziee_GGAPP \
            -Dsonar.organization=webziee \
            -Dsonar.host.url=https://sonarcloud.io
