name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK (Required for building Android project)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Grant execute permission for gradlew (If needed)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Build with Gradle (this step builds your Android project)
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
