name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK (Java is needed for Android builds)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build the Android project
      - name: Build with Gradle
        run: ./gradlew build

      # Initialize CodeQL (set the language as Java/Kotlin)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'

      # Create CodeQL database (runs after the build)
      - name: Build CodeQL database
        run: ./gradlew build

      # Run CodeQL analysis
      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2
